[2022-06-27 13:33:31,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-06-25T00:00:00+00:00 [queued]>
[2022-06-27 13:33:31,906] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-06-25T00:00:00+00:00 [queued]>
[2022-06-27 13:33:31,907] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:31,908] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:33:31,909] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:31,926] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-25 00:00:00+00:00
[2022-06-27 13:33:31,936] {standard_task_runner.py:52} INFO - Started process 58657 to run task
[2022-06-27 13:33:31,948] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-06-25T00:00:00+00:00', '--job-id', '900', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpomubmzs6', '--error-file', '/tmp/tmpv7xqz5hp']
[2022-06-27 13:33:31,949] {standard_task_runner.py:80} INFO - Job 900: Subtask inaccurate
[2022-06-27 13:33:32,068] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-06-25T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:33:32,159] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T00:00:00+00:00
[2022-06-27 13:33:32,162] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:33:32,164] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:33:32,176] {subprocess.py:85} INFO - Output:
[2022-06-27 13:33:32,179] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:33:32,180] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:33:32,212] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220625T000000, start_date=20220627T133331, end_date=20220627T133332
[2022-06-27 13:33:32,237] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:33:32,262] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
