[2022-06-27 13:32:07,443] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-03-31T00:00:00+00:00 [queued]>
[2022-06-27 13:32:07,456] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-03-31T00:00:00+00:00 [queued]>
[2022-06-27 13:32:07,457] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:07,458] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:32:07,462] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:07,496] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-03-31 00:00:00+00:00
[2022-06-27 13:32:07,504] {standard_task_runner.py:52} INFO - Started process 57673 to run task
[2022-06-27 13:32:07,518] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-03-31T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpfvi3bb4t', '--error-file', '/tmp/tmplqllpzih']
[2022-06-27 13:32:07,521] {standard_task_runner.py:80} INFO - Job 473: Subtask inaccurate
[2022-06-27 13:32:07,604] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-03-31T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:32:07,716] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T00:00:00+00:00
[2022-06-27 13:32:07,720] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:32:07,721] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:32:07,748] {subprocess.py:85} INFO - Output:
[2022-06-27 13:32:07,756] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:32:07,760] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:32:07,885] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220331T000000, start_date=20220627T133207, end_date=20220627T133207
[2022-06-27 13:32:07,970] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:32:08,012] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
