[2022-06-27 13:33:20,669] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-27 13:33:20,721] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-27 13:33:20,723] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:20,729] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:33:20,731] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:20,831] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-06 00:00:00+00:00
[2022-06-27 13:33:20,890] {standard_task_runner.py:52} INFO - Started process 58523 to run task
[2022-06-27 13:33:20,943] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '841', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpcu7wj7vo', '--error-file', '/tmp/tmpdqosu7tp']
[2022-06-27 13:33:20,949] {standard_task_runner.py:80} INFO - Job 841: Subtask inaccurate
[2022-06-27 13:33:21,227] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-06-06T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:33:21,544] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-27 13:33:21,547] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:33:21,551] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:33:21,663] {subprocess.py:85} INFO - Output:
[2022-06-27 13:33:21,695] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:33:21,717] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:33:21,777] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220606T000000, start_date=20220627T133320, end_date=20220627T133321
[2022-06-27 13:33:21,915] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:33:21,946] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
