[2022-06-27 13:33:06,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2022-06-27 13:33:06,483] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2022-06-27 13:33:06,484] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:06,485] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:33:06,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:33:06,511] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-05-26 00:00:00+00:00
[2022-06-27 13:33:06,523] {standard_task_runner.py:52} INFO - Started process 58357 to run task
[2022-06-27 13:33:06,553] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-05-26T00:00:00+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpcnnhtjdq', '--error-file', '/tmp/tmpddg41ibi']
[2022-06-27 13:33:06,558] {standard_task_runner.py:80} INFO - Job 770: Subtask inaccurate
[2022-06-27 13:33:06,702] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-05-26T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:33:06,811] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-26T00:00:00+00:00
[2022-06-27 13:33:06,814] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:33:06,816] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:33:06,859] {subprocess.py:85} INFO - Output:
[2022-06-27 13:33:06,864] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:33:06,865] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:33:06,901] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220526T000000, start_date=20220627T133306, end_date=20220627T133306
[2022-06-27 13:33:06,963] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:33:06,991] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
