[2022-06-27 13:31:53,275] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-06-27 13:31:53,319] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-06-27 13:31:53,321] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:53,321] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:53,323] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:53,351] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-03-13 00:00:00+00:00
[2022-06-27 13:31:53,368] {standard_task_runner.py:52} INFO - Started process 57523 to run task
[2022-06-27 13:31:53,376] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpjn9sunnu', '--error-file', '/tmp/tmpnwldq22y']
[2022-06-27 13:31:53,380] {standard_task_runner.py:80} INFO - Job 411: Subtask inaccurate
[2022-06-27 13:31:53,619] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-03-13T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:54,512] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-06-27 13:31:54,543] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:31:54,553] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:31:54,844] {subprocess.py:85} INFO - Output:
[2022-06-27 13:31:54,937] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:31:54,958] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:31:55,300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220313T000000, start_date=20220627T133153, end_date=20220627T133155
[2022-06-27 13:31:55,451] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:55,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
