[2022-06-27 13:31:36,866] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-02-26T00:00:00+00:00 [queued]>
[2022-06-27 13:31:36,892] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-02-26T00:00:00+00:00 [queued]>
[2022-06-27 13:31:36,895] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:36,896] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:36,900] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:36,920] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-02-26 00:00:00+00:00
[2022-06-27 13:31:36,932] {standard_task_runner.py:52} INFO - Started process 57334 to run task
[2022-06-27 13:31:36,943] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-02-26T00:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp7riat4hn', '--error-file', '/tmp/tmp0zyv9pn9']
[2022-06-27 13:31:36,944] {standard_task_runner.py:80} INFO - Job 325: Subtask inaccurate
[2022-06-27 13:31:37,039] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-02-26T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:37,128] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-02-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-26T00:00:00+00:00
[2022-06-27 13:31:37,133] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:31:37,136] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:31:37,186] {subprocess.py:85} INFO - Output:
[2022-06-27 13:31:37,192] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:31:37,194] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:31:37,284] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220226T000000, start_date=20220627T133136, end_date=20220627T133137
[2022-06-27 13:31:37,352] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:37,412] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
