[2022-06-27 13:30:54,109] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-01-19T00:00:00+00:00 [queued]>
[2022-06-27 13:30:54,159] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.inaccurate scheduled__2022-01-19T00:00:00+00:00 [queued]>
[2022-06-27 13:30:54,163] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:30:54,165] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:30:54,167] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:30:54,278] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-01-19 00:00:00+00:00
[2022-06-27 13:30:54,329] {standard_task_runner.py:52} INFO - Started process 56939 to run task
[2022-06-27 13:30:54,361] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'inaccurate', 'scheduled__2022-01-19T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp68pkjlxs', '--error-file', '/tmp/tmp6zxpi19j']
[2022-06-27 13:30:54,394] {standard_task_runner.py:80} INFO - Job 163: Subtask inaccurate
[2022-06-27 13:30:54,664] {task_command.py:370} INFO - Running <TaskInstance: dag1.inaccurate scheduled__2022-01-19T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:30:54,958] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-19T00:00:00+00:00
[2022-06-27 13:30:54,966] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 13:30:54,971] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 13:30:55,107] {subprocess.py:85} INFO - Output:
[2022-06-27 13:30:55,110] {subprocess.py:92} INFO - inaccurate
[2022-06-27 13:30:55,116] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-27 13:30:55,170] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=inaccurate, execution_date=20220119T000000, start_date=20220627T133054, end_date=20220627T133055
[2022-06-27 13:30:55,559] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:30:55,730] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
